import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const FONT_SIZE = 10;
const HEADER_FONT = 14;
const TITLE_FONT = 12;

export function createPayslipPdf(params: {
  employeeName: string;
  employeeType: string;
  month: string;
  monthLabel: string;
  baseAmount: number;
  addDeductAmount: number;
  addDeductRemarks: string;
  pfDeducted: number;
  esiDeducted: number;
  advanceDeducted: number;
  totalPayable: number;
  paymentAmount: number;
  paymentMode: string;
  bankName?: string;
  accountNumber?: string;
}): Uint8Array {
  const doc = new jsPDF();
  const y = 20;

  doc.setFontSize(HEADER_FONT);
  doc.text('PAYSLIP', 105, y, { align: 'center' });
  doc.setFontSize(FONT_SIZE);

  let yPos = y + 15;
  doc.text(`Employee: ${params.employeeName}`, 20, yPos);
  yPos += 7;
  doc.text(`Month: ${params.monthLabel}`, 20, yPos);
  yPos += 7;
  doc.text(`Type: ${params.employeeType === 'full_time' ? 'Full Time' : 'Contractor'}`, 20, yPos);
  yPos += 12;

  const body: string[][] = [['Base Amount', params.baseAmount.toLocaleString('en-IN')]];
  if (params.addDeductAmount !== 0) {
    body.push([params.addDeductRemarks || 'Add/Deduct', params.addDeductAmount.toLocaleString('en-IN')]);
  }
  body.push(['Gross Payable', params.totalPayable.toLocaleString('en-IN')]);
  if (params.pfDeducted > 0) body.push(['PF Deducted', `-${params.pfDeducted.toLocaleString('en-IN')}`]);
  if (params.esiDeducted > 0) body.push(['ESI Deducted', `-${params.esiDeducted.toLocaleString('en-IN')}`]);
  if (params.advanceDeducted > 0) body.push(['Advance Deducted', `-${params.advanceDeducted.toLocaleString('en-IN')}`]);
  body.push(['Net Pay', params.paymentAmount.toLocaleString('en-IN')]);
  body.push(['Payment Mode', params.paymentMode]);
  if (params.bankName) body.push(['Bank', params.bankName]);
  if (params.accountNumber) body.push(['Account', `****${String(params.accountNumber).slice(-4)}`]);

  autoTable(doc, {
    startY: yPos,
    head: [['Particulars', 'Amount (₹)']],
    body,
    theme: 'plain',
    headStyles: { fillColor: [71, 85, 105] },
    margin: { left: 20, right: 20 },
  });

  doc.setFontSize(9);
  doc.text('Generated by URBAN FASHION FACTORY', 105, doc.internal.pageSize.height - 10, { align: 'center' });

  return new Uint8Array(doc.output('arraybuffer'));
}

export function createPaymentSummaryPdf(params: {
  month: string;
  monthLabel: string;
  rows: { employeeName: string; totalPayable: number; paymentAmount: number; paymentMode: string }[];
  total: number;
}): Uint8Array {
  const doc = new jsPDF('landscape');
  const y = 20;

  doc.setFontSize(HEADER_FONT);
  doc.text('PAYMENT SUMMARY', 148, y, { align: 'center' });
  doc.setFontSize(FONT_SIZE);
  doc.text(`Month: ${params.monthLabel}`, 20, y + 10);
  doc.text(`Total: ₹${params.total.toLocaleString('en-IN')}`, 20, y + 17);

  const body = params.rows.map((r) => [
    r.employeeName,
    r.totalPayable.toLocaleString('en-IN'),
    r.paymentAmount.toLocaleString('en-IN'),
    r.paymentMode,
  ]);

  autoTable(doc, {
    startY: y + 25,
    head: [['Employee', 'Total Payable (₹)', 'Paid (₹)', 'Mode']],
    body,
    theme: 'striped',
    headStyles: { fillColor: [71, 85, 105] },
    margin: { left: 20, right: 20 },
  });

  doc.setFontSize(9);
  doc.text('Generated by URBAN FASHION FACTORY', 148, doc.internal.pageSize.height - 10, { align: 'center' });

  return new Uint8Array(doc.output('arraybuffer'));
}

export function createMonthlyReportPdf(params: {
  month: string;
  monthLabel: string;
  totalPayments: number;
  totalWorkAmount: number;
  employeeCount: number;
  paymentCount: number;
  byBranch: { branchName: string; workAmount: number; paymentAmount: number }[];
}): Uint8Array {
  const doc = new jsPDF();
  let y = 20;

  doc.setFontSize(HEADER_FONT);
  doc.text('MONTHLY REPORT', 105, y, { align: 'center' });
  doc.setFontSize(FONT_SIZE);
  y += 15;

  doc.text(`Month: ${params.monthLabel}`, 20, y);
  y += 10;
  doc.text(`Total Payments: ₹${params.totalPayments.toLocaleString('en-IN')}`, 20, y);
  y += 7;
  doc.text(`Total Work Amount: ₹${params.totalWorkAmount.toLocaleString('en-IN')}`, 20, y);
  y += 7;
  doc.text(`Employees: ${params.employeeCount}`, 20, y);
  y += 7;
  doc.text(`Payment Transactions: ${params.paymentCount}`, 20, y);
  y += 15;

  if (params.byBranch.length > 0) {
    doc.setFontSize(TITLE_FONT);
    doc.text('Branch-wise Summary', 20, y);
    doc.setFontSize(FONT_SIZE);
    y += 8;

    const body = params.byBranch.map((b) => [
      b.branchName,
      b.workAmount.toLocaleString('en-IN'),
      b.paymentAmount.toLocaleString('en-IN'),
    ]);

    autoTable(doc, {
      startY: y,
      head: [['Branch', 'Work Amount (₹)', 'Payments (₹)']],
      body,
      theme: 'striped',
      headStyles: { fillColor: [71, 85, 105] },
      margin: { left: 20, right: 20 },
    });
  }

  doc.setFontSize(9);
  doc.text('Generated by URBAN FASHION FACTORY', 105, doc.internal.pageSize.height - 10, { align: 'center' });

  return new Uint8Array(doc.output('arraybuffer'));
}
